import { Layout } from "@/components/layouts";
import { Typography } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jira Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout title="Jira App">
          <Typography variant="h1" color="primary">
            Hello world!
          </Typography>
        </Layout>
      </main>
    </>
  );
}
