import Head from "next/head";
import React from "react";
import Navbar from "../Navbar";
import styles from "@/styles/Home.module.css";

const MainLayout = ({ children }: { children: JSX.Element }) => {
  return (
    <>
      <Head>
        <title>Home | My first Next.js app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>{children}</main>
    </>
  );
};

export default MainLayout;
